### ISSUE TITLE
Package inconsistency in lan-simulator

### ISSUE THREAD

**Issue by Uko** [cdlm/pharo-katas#2]
In the tutorial text from time to time you use `NetworkSimulator` package while in other places `Kata-NetworkSimulator`.

Example:
https://github.com/cdlm/pharo-katas/blob/master/lan-simulator.pillar#L30
https://github.com/cdlm/pharo-katas/blob/master/lan-simulator.pillar#L66

**Comment by Ducasse** [comment]
Yes I would like to remove Kata-....

Stef

**Comment by cdlm** [comment]
I would have preferred to have Pillar include the actual code from Filetree in the text. Copy-pasting was the quick-n-dirty way (and it's necessary for class declarations anyway)

**Comment by Ducasse** [comment]
On 07 Nov 2015, at 13:38, Damien Pollet notifications@github.com wrote:

> I would have preferred to have Pillar include the actual code from Filetree in the text. Copy-pasting was the quick-n-dirty way (and it's necessary for class declarations anyway)
> 
> Not really because you can have multiple version of the same methods and the farthest I’m from git the better
> 
> —
> Reply to this email directly or view it on GitHub.

---

Stéphane Ducasse
http://stephane.ducasse.free.fr
http://www.synectique.eu / http://www.pharo.org 
03 59 35 87 52
Assistant: Julie Jonas 
03 59 57 78 50
03 59 35 86 16

S. Ducasse - Inria
40, avenue Halley, 
Parc Scientifique de la Haute Borne, Bât.A, Park Plaza
Villeneuve d'Ascq 59650
France
